FROM node:20-alpine
RUN apk add --no-cache curl

WORKDIR /usr/src/app

COPY apps/OpenSign/package*.json ./
RUN npm ci

COPY apps/OpenSign/server.cjs ./
COPY apps/OpenSign/entrypoint.sh ./
COPY apps/OpenSign/build/ ./build/

RUN chmod +x entrypoint.sh

EXPOSE 3000

CMD ["./entrypoint.sh", "npm", "start"]
